FROM docker.io/golang:1.19-alpine

RUN apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing vips-dev && \
    apk add \
      git \
      make \
      gcc \
      musl-dev && \
    go install github.com/go-delve/delve/cmd/dlv@v1.9.1

ADD https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64 /usr/bin/tailwindcss
RUN chmod +x /usr/bin/tailwindcss

RUN mkdir -p /app
COPY go.mod /app
COPY go.sum /app
WORKDIR /app
RUN go mod download -x

# TODO: Pre-build the app for faster bootup idk?
ADD . /app
WORKDIR /app
RUN tailwindcss -c ./internal/api/web/tailwind.config.js -i ./internal/api/web/style.css -o ./internal/api/web/embed/assets/css/style.css
