---
- name: Install iptables-persistent
  apt: name=iptables-persistent state=latest

- name: Get iptables rules
  shell: /sbin/iptables -L
  register: iptablesrules
  always_run: yes

- name: Add conntrack rule
  command: /sbin/iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT -m comment --comment "Conntrack"
  when: iptablesrules.stdout.find("Conntrack") == -1

- name: Add ssh iptables rule
  command: /sbin/iptables -A INPUT -p tcp --dport 22 -j ACCEPT -m comment --comment "SSH"
  when: iptablesrules.stdout.find("SSH") == -1

- name: Add nginx iptables rule
  command: /sbin/iptables -I INPUT -p tcp --dport 80 -j ACCEPT -m comment --comment "Nginx_HTTP"
  when: iptablesrules.stdout.find("Nginx_HTTP") == -1

- name: Add nginx ssl iptables rule
  command: /sbin/iptables -I INPUT -p tcp --dport 443 -j ACCEPT -m comment --comment "Nginx_SSL"
  when: iptablesrules.stdout.find("Nginx_SSL") == -1

- name: Add local interface iptables rule
  command: /sbin/iptables -I INPUT -i lo -j ACCEPT -m comment --comment "Local"
  when: iptablesrules.stdout.find("Local") == -1

- name: Add socket.io iptables rule
  command: /sbin/iptables -I INPUT -p tcp --dport 4000 -j ACCEPT -m comment --comment "SocketIO"
  when: iptablesrules.stdout.find("SocketIO") == -1

- name: Add default iptables policy
  command: /sbin/iptables -P INPUT DROP

- name: Save iptables
  shell: /sbin/iptables-save > /etc/iptables/rules.v4