FROM docker.io/golang:1.19-alpine

RUN apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing vips-dev && \
    apk add \
      pkgconfig \
      gcc \
      musl-dev && \
    go install github.com/go-delve/delve/cmd/dlv@v1.9.1

COPY go.mod go.sum /app/
WORKDIR /app
RUN go mod download -x

ADD . /app
WORKDIR /app
